[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170724213527-c4b2de4/master-haskell-20170724213527-c4b2de4"
  version = 1
  sha1 = "09aa2a97367596116e8d12112bf68464919d4815"

[global]
  CACHE = "false"

[build.dist]
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.dist-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.branches-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.dist-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

[build.branches-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

[build.dist-7-10-cabal-test]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  TEST = "false"
  CABAL_TEST = "true"

[build.branches-7-10-cabal-test]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  TEST = "false"
  CABAL_TEST = "true"

[build.dist-8-0-cabal-test]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"
  TEST = "false"
  CABAL_TEST = "true"

[build.branches-8-0-cabal-test]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"
  TEST = "false"
  CABAL_TEST = "true"
